services:
  web:
    build: 
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - bundle:/usr/local/bundle:delegated
      - cache:/app/tmp/cache:delegated
      - .:/app:cached
    ports:
      - "3000:3000"
    tty: true
    environment:
      RAILS_ENV: development

volumes:
  bundle:
  cache:
